minespeak

func Test2() do

endfunc

func Test(param1:num) -> bool do

    do
    var n : num = 2 + 3

    while 2+2             endwhile

    var i : num = 5
/*
    for var gamer : bool = 2, sebastian : bool = true, jacob : bool = 25 until i > 10 where i += 1 do
        var n : num = 2 + 3
    endfor

    var flag : num = 2

    if flag do

    endif
*/
    Test2(1)

    return true
endfunc



closespeak